<a href="https://colab.research.google.com/github/Poohi5/cmpe258_homework_0/blob/master/NumpyArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Numpy Array Attributes

In [0]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(12, size=(1, 2, 3))  # Three-dimensional array

In [7]:
print("x1 ndim: ", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size: ", x1.size)

x1 ndim:  3
x1 shape: (1, 2, 3)
x1 size:  6


In [8]:
print(x1)

[[[ 5  0  3]
  [11  3  7]]]


######Array datatype

In [9]:
x1.dtype

dtype('int64')

In [0]:
x2 = np.random.randint(10, size=6)

In [14]:
x2

array([9, 3, 5, 2, 4, 7])

#####To access elements of an array

In [13]:
x2[0] #Gives access to 1st element of the array

9

In [15]:
x2[3]

2

In [16]:
x2[-1]

7

In [17]:
x1

array([[[ 5,  0,  3],
        [11,  3,  7]]])

In [22]:
x1[0,0] #get access to 3 dimensional array

array([5, 0, 3])

#####Slicing Array

In [23]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [24]:
a[:0]

array([], dtype=int64)

In [25]:
a[:5]

array([0, 1, 2, 3, 4])

In [26]:
a[:-1]

array([0, 1, 2, 3])

In [27]:
a[-1:]

array([4])

In [28]:
a[::-1]

array([4, 3, 2, 1, 0])

In [0]:
y = np.random.randint(10, size=(3, 4))  # Two-dimensional array

In [30]:
y

array([[6, 8, 8, 1],
       [6, 7, 7, 8],
       [1, 5, 9, 8]])

In [31]:
y[:2, :1] #2 rows and 1 column

array([[6],
       [6]])

In [32]:
y[:3, :4] 

array([[6, 8, 8, 1],
       [6, 7, 7, 8],
       [1, 5, 9, 8]])

In [33]:
y[:1, ::2] #1st row, alt columns

array([[6, 8]])

In [34]:
y[:3, ::2] #3 row, alt columns

array([[6, 8],
       [6, 7],
       [1, 9]])

In [35]:
y[::-1, ::-1]

array([[8, 9, 5, 1],
       [8, 7, 7, 6],
       [1, 8, 8, 6]])

##Array Reshaping

In [36]:
r = np.arange(1, 10).reshape((3, 3))  #3x3 matrix using reshape
print(r)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [38]:
x.shape

(3,)

In [39]:
x.size

3

In [40]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [41]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])